dist: trusty
sudo: required
language: bash
before_install: 
    - url https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh | bash
notifications:
    slack:
        rooms:
            secure:
k8vrUbkEVVsTt6GNDajt1qHYvJeLlQlh7gLjW/qPpNZOBVsuQbIVgv/baYc9SaRrlRoa8g/tc/XXo+u0fvvjlMORlejQkRQdkGZnGW0MUSZgA2cvAJuZ2LnQDSFj+KK/i3qkF/11V2p6kropIefJtMZvaNO900akGxHzzHXT3nS5HrdKVu9EpvOoLIm9952I265Q3omxU2LyubaWkNc1ane6HBmxFn7g5d0SQtKyQI+TsgWLz0BCquBhAGuFTjNepQVuOegRLpENcUPVs/5jP9z4YLFfiUz6NbqpYD3x2g0fRk0LcFfDDmzOQczgIBOKDANmf7qXvoHxloC7uv73nGJ6THtT/+ekP1jUQU7b22w6HX3yYsbiZX0mFEOsJdmnVW63PB/5pXmeUVUqPUXnQ1V9RxxO95mN44f6y+2FF91wyJJlfRBk4wbOwdphMJExA2N7JrUH6uHcLTw7xDwozr1lOzUQulQT3eWaqxEjnbIXHGG43mRnTQYCuqfFeQA8093QKNHCApul7IzcrJ6ajLrX0mDjm3NZO7qV3fJ6eyBtgOSp8TJfP44hZJs6lB5J9GQ326WQTZpDAfnVUQAm3kZmsDWJh0l/b5/Uq7LA5xN43rBKCgfcxH6cYhNN7Aam1gPdOHUxRWYLxwQmLN8ZsuroD5I+8L0DndHdm5t6SEw=
